#! /bin/bash

if [[ "$DB_TYPE" == "postgres" ]];
then
    PGPASSWORD=$DB_PASSWORD psql --host=$DB_HOST --port=$DB_PORT --username=$DB_USER --dbname=$DB_DATABASE
else
    echo "DB_TYPE $DB_TYPE not implemented."
    exit
fi
